#!/bin/bash

KICK_ASS_DOTFILES_HOME=$HOME/.kickassdotfiles

function log {
  echo "~ $1"
}

function configureVim {
  log "vim"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  git submodule update --init --recursive
  mkdir -p $HOME/.vim/spell
  ln -sf $KICK_ASS_DOTFILES_HOME/vim/en.utf-8.add $HOME/.vim/spell/en.utf-8.add
  ln -sf $KICK_ASS_DOTFILES_HOME/vim/vimrc $HOME/.vimrc
}

function configureFzf {
  log "fzf"
  ln -sf $KICK_ASS_DOTFILES_HOME/ag/agignore $HOME/.agignore
}

function configureZsh {
  log "zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ln -sf $KICK_ASS_DOTFILES_HOME/oh-my-zsh/zshrc $HOME/.zshrc
  ln -sf $KICK_ASS_DOTFILES_HOME/oh-my-zsh/chuckbadass.zsh-theme $HOME/.oh-my-zsh/themes/chuckbadass.zsh-theme
}

function configureProfile {
  log "profile"
  ln -sf $KICK_ASS_DOTFILES_HOME/linux/profile $HOME/.profile
}

function configureI3wm {
  log "i3-wm"
  mkdir -p $HOME/.i3
  sudo ln -sf $KICK_ASS_DOTFILES_HOME/i3/i3exit /usr/local/bin/i3exit
  ln -sf $KICK_ASS_DOTFILES_HOME/i3/config $HOME/.i3/config

  log "i3-wm:polybar"
  mkdir -p $HOME/.config/polybar
  ln -sf $KICK_ASS_DOTFILES_HOME/polybar/config.ini $HOME/.config/polybar/config.ini
  ln -sf $KICK_ASS_DOTFILES_HOME/polybar/launch.sh $HOME/.config/polybar/launch.sh
  chmod +x $HOME/.config/polybar/launch.sh
}

function configureGit {
  log "git"
  ln -sf $KICK_ASS_DOTFILES_HOME/git/gitconfig $HOME/.gitconfig
  ln -sf $KICK_ASS_DOTFILES_HOME/git/gitignore_global $HOME/.gitignore_global
}

function configureMotion {
  log "motion"
  mkdir -p $HOME/.motion
  ln -sf $KICK_ASS_DOTFILES_HOME/motion/motion.conf $HOME/.motion/motion.conf
}

function configurePicom {
  log "picom (formerly compton)"
  mkdir -p $HOME/.config/picom
  ln -sf $KICK_ASS_DOTFILES_HOME/picom/config $HOME/.config/picom/picom.conf
}

function configureDiffSoFancy {
  log "diff-so-fancy"
  sudo ln -sf $KICK_ASS_DOTFILES_HOME/vim/diff-so-fancy/diff-so-fancy /usr/local/bin/diff-so-fancy
}

case "$1" in
  fzf)
    configureFzf
    ;;
  vim)
    configureVim
    ;;
  zsh)
    configureZsh
    ;;
  profile)
    configureProfile
    ;;
  i3)
    configureI3wm
    ;;
  git)
    configureGit
    ;;
  diffsofancy)
    configureDiffSoFancy
    ;;
  motion)
    configureMotion
    ;;
  picom)
    configurePicom
    ;;
  -h|h|help|--help)
    echo "Usage:
      ./install             # Install all config files (will overwrite any existing configuration)
      ./install tool-name   # Install configuration for 'tool-name'"
    ;;
  *)
    # Sanity check
    ./misc/confirm.sh "Bruv, are you sure you want to do this? Current config that isn't managed by me will be overwitten [y/N] "
    RESULT=$?
    [ $RESULT -ne 0 ] && exit 0

    # Proceed with the installation of everything
    configureFzf
    configureVim
    configureZsh
    configureProfile
    configureI3wm
    configureGit
    configureDiffSoFancy
    configurePicom
    ;;
esac

exit 0
