#!/bin/bash

# Sanity check
./general/confirm.sh "Bruv, are you sure you want to do this? Current config that isn't managed by me will be overwitten [y/N] "
RESULT=$?
[ $RESULT -ne 0 ] && exit 0

# Proceed with the installation
KICK_ASS_CONFIGS_HOME=$HOME/.kickassconfigs

function log {
  echo "~ $1"
}

function configureVim {
  log "vim"
  mkdir -p $HOME/.vim/spell
  ln -sf $KICK_ASS_CONFIGS_HOME/vim/en.utf-8.add $HOME/.vim/spell/en.utf-8.add
  ln -sf $KICK_ASS_CONFIGS_HOME/vim/vimrc $HOME/.vimrc
}

function configureFzf {
  log "fzf"
  ln -sf $KICK_ASS_CONFIGS_HOME/ag/agignore $HOME/.agignore
}

function configureZsh {
  log "zsh"
  mkdir -p $HOME/.oh-my-zsh/themes
  ln -sf $KICK_ASS_CONFIGS_HOME/oh-my-zsh/zshrc $HOME/.zshrc
  ln -sf $KICK_ASS_CONFIGS_HOME/oh-my-zsh/chuckbadass.zsh-theme $HOME/.oh-my-zsh/themes/chuckbadass.zsh-theme
}

function configureProfile {
  log "profile"
  ln -sf $KICK_ASS_CONFIGS_HOME/linux/profile $HOME/.profile
}

function configureI3wm {
  log "i3-wm"
  mkdir -p $HOME/.config/i3status $HOME/.i3
  sudo ln -sf $KICK_ASS_CONFIGS_HOME/i3/i3exit /usr/local/bin/i3exit
  ln -sf $KICK_ASS_CONFIGS_HOME/i3/config $HOME/.i3/config
  ln -sf $KICK_ASS_CONFIGS_HOME/i3/i3status.conf $HOME/.config/i3status/config
}

function configureGit {
  log "git"
  ln -sf $KICK_ASS_CONFIGS_HOME/git/gitconfig $HOME/.gitconfig
  ln -sf $KICK_ASS_CONFIGS_HOME/git/gitignore_global $HOME/.gitignore_global
}

function installDiffSoFancy {
  log "diff-so-fancy"
  sudo ln -sf $KICK_ASS_CONFIGS_HOME/vim/diff-so-fancy/diff-so-fancy /usr/local/bin/diff-so-fancy
}

configureFzf
configureVim
configureZsh
configureProfile
configureI3wm
configureGit
installDiffSoFancy

exit 0
