#!/bin/zsh

if [ $# -eq 0 ]; then
	echo "Usage: $0 up|down";
	exit 1;
fi

BRIGHTNESS=$(xrandr --verbose | awk '/Brightness/ { print $2; exit }')

if [ "$1" '==' "up" ]; then
  xrandr --output eDP-1 --brightness $(($BRIGHTNESS + 0.1))
elif [ "$1" '==' "down" ]; then
  xrandr --output eDP-1 --brightness $(($BRIGHTNESS - 0.1))
elif [ "$1" '==' "reset" ]; then
  xrandr --output eDP-1 --brightness 1.0
fi

