#!/bin/zsh

BRIGHTNESS=$(xrandr --verbose | awk '/Brightness/ { print $2; exit }')

if [ "$1" '==' "+" ] && (( $BRIGHTNESS < 1.0 )); then
  xrandr --output eDP-1 --brightness $(($BRIGHTNESS + 0.1))
elif [ "$1" '==' "-" ] && (( $BRIGHTNESS > 0.0 )); then
  xrandr --output eDP-1 --brightness $(($BRIGHTNESS - 0.1))
else
  xrandr --output eDP-1 --brightness 1.0
fi

