# Breeze Dark

$font = Noto Sans

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgba(926ee4ee) rgba(7256d0e0) 45deg
    check_color = rgba(926ee4ee) rgba(27ae60ee) 120deg
    fail_color = rgba(da4453ee) rgba(c0392bee) 40deg

    font_color = rgb(fcfcfc)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgb(fcfcfc)

    position = -30, 0
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font
    color = rgb(a1a9b1)

    position = -30, -150
    halign = right
    valign = top
}
